# Generated by Django 2.0.6 on 2019-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('marry', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('academic', models.CharField(blank=True, max_length=255, null=True)),
                ('nation', models.CharField(blank=True, max_length=255, null=True)),
                ('politics', models.CharField(blank=True, max_length=255, null=True)),
                ('exper', models.CharField(blank=True, max_length=255, null=True)),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('census', models.CharField(blank=True, max_length=255, null=True)),
                ('job_status', models.CharField(blank=True, max_length=255, null=True)),
                ('job_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('job_p', models.CharField(blank=True, max_length=255, null=True)),
                ('job_ind', models.CharField(blank=True, max_length=255, null=True)),
                ('job_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('edu', models.TextField(blank=True, null=True)),
                ('null1', models.CharField(blank=True, max_length=255, null=True)),
                ('null2', models.CharField(blank=True, max_length=255, null=True)),
                ('null3', models.CharField(blank=True, max_length=255, null=True)),
                ('null4', models.CharField(blank=True, max_length=255, null=True)),
                ('null5', models.CharField(blank=True, max_length=255, null=True)),
                ('job_exp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_info',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('null', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('is_lock', models.CharField(default='2', max_length=32)),
            ],
        ),
    ]
